name: "tka_seg_2nd_0"
platform: "tensorflow_graphdef"
max_batch_size: 1
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [ 1, 192, 112, 112 ]
  }
]
output [
  {
    name: "last_softmax_out"
    data_type: TYPE_FP32
    dims: [ 3, 192, 112, 112 ]
  }
]
default_model_filename: "model.onnx"